IMGUR_REFRESH_TOKEN = ""
IMGUR_ACCESS_TOKEN = ""
IMGUR_CLIENT_ID = ""
IMGUR_SECRET_ID = ""


AUTH_TOKEN ="MjM2MzQxMTkzODQyMDk4MTc3.C1IiGA.ZYgyS-gVE08Ww-M-QVGiGi8k5Fg"

APSIS_AUTH_TOKEN = "MjYxMDI4OTIyODk5MTY5Mjgw.Czu-AA.AB44YQ5__R-kbF8UfEUjrCeWgfs"

USER_AUTH_TOKEN = ""


DISCORD_PASSWORD = ""

MONGO_USN = ""
MONGO_PASS = ""
MONGO_SITE = ""

